Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurricularizacaoADS2024.Models;

namespace CurricularizacaoADS2024.Controllers
{
    public class AlunosController : Controller
    {
        private readonly Contexto _context;

        public AlunosController(Contexto context)
        {
            _context = context;
        }

        // GET: Alunos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alunos.ToListAsync());
        }

        // GET: Alunos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Nascimento,Endereco,CPF,RG,Telefone,Sexo")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aluno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos.FindAsync(id);
            if (aluno == null)
            {
                return NotFound();
            }
            return View(aluno);
        }

        // POST: Alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Nascimento,Endereco,CPF,RG,Telefone,Sexo")] Aluno aluno)
        {
            if (id != aluno.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunoExists(aluno.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        // GET: Alunos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aluno = await _context.Alunos.FindAsync(id);
            if (aluno != null)
            {
                _context.Alunos.Remove(aluno);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunoExists(int id)
        {
            return _context.Alunos.Any(e => e.Id == id);
        }
    }
}

Controllers/ConsultasController.cs
using CurricularizacaoADS2024.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace CurricularizacaoADS2024.Controllers
{
    public class ConsultasController : Controller
    {
        private readonly Contexto contexto;

        public ConsultasController(Contexto context)
        {
            contexto = context;
        }
        public IActionResult FiltrarVisita ()
        {
            return View();
        }

        public IActionResult ResFiltrarVisita(int ?id, string nome) 
        { 
            List<Visita> listaVisitas = new List<Visita>();
            if (id != null)
               listaVisitas = contexto.Visitas.Include(t=>t.responsavel).Where(t => t.Id==id).ToList();

            else 
                if (! nome.IsNullOrEmpty())
                //listaVisitas = contexto.Visitas.Include(t => t.responsavel).Where(n=> n.responsavel.nome == nome).ToList();
                listaVisitas = contexto.Visitas.Include(t => t.responsavel).Where(n=> n.responsavel.nome.Contains(nome)).OrderBy(o=>o.responsavel.nome).ToList();
                 else
                        listaVisitas = contexto.Visitas.Include(t => t.responsavel).ToList();

            return View(listaVisitas);
        }

        public IActionResult FiltrarMatricula ()
        { 
            return View(); 
        }


        public IActionResult ResFiltraMatricula(int? id, string nome)
        {
            List<Matricula> listaMatricula;

            if (id != null)
            {
                listaMatricula = contexto.Matriculas
                    .Include(a => a.aluno)
                    .Include(a => a.turma)
                    .Include(a => a.curso)
                    .Where(a => a.Id == id)
                    .ToList();
            }

            else
                if(!nome.IsNullOrEmpty()) 
            {
                listaMatricula = contexto.Matriculas
                    .Include(a => a.aluno)
                    .Include(a => a.turma)
                    .Include(a => a.curso)
                    .Where(n => n.aluno.Nome.Contains(nome)). OrderBy(o=>o.aluno.Nome)
                    .ToList();
            }

            else
            {
                listaMatricula = contexto.Matriculas
                    .Include(a => a.aluno)
                    .Include(a => a.turma)
                    .Include(a => a.curso)
                    .ToList();
            }

            return View(listaMatricula);
        }



    }
}

Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurricularizacaoADS2024.Models;

namespace CurricularizacaoADS2024.Controllers
{
    public class CursosController : Controller
    {
        private readonly Contexto _context;

        public CursosController(Contexto context)
        {
            _context = context;
        }

        // GET: Cursos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cursos.ToListAsync());
        }

        // GET: Cursos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // GET: Cursos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Cursos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // POST: Cursos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao")] Curso curso)
        {
            if (id != curso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: Cursos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Cursos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = await _context.Cursos.FindAsync(id);
            if (curso != null)
            {
                _context.Cursos.Remove(curso);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _context.Cursos.Any(e => e.Id == id);
        }
    }
}

Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurricularizacaoADS2024.Models;

namespace CurricularizacaoADS2024.Controllers
{
    public class TurmasController : Controller
    {
        private readonly Contexto _context;

        public TurmasController(Contexto context)
        {
            _context = context;
        }

        // GET: Turmas
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Turma.Include(t => t.atidade);
            return View(await contexto.ToListAsync());
        }

        // GET: Turmas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turma = await _context.Turma
                .Include(t => t.atidade)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (turma == null)
            {
                return NotFound();
            }

            return View(turma);
        }

        // GET: Turmas/Create
        public IActionResult Create()
        {
            ViewData["atividadeID"] = new SelectList(_context.Set<Atividade>(), "Id", "Nome");
            return View();
        }

        // POST: Turmas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,descricao,periodo,atividadeID")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                _context.Add(turma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["atividadeID"] = new SelectList(_context.Set<Atividade>(), "Id", "Nome", turma.atividadeID);
            return View(turma);
        }

        // GET: Turmas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turma = await _context.Turma.FindAsync(id);
            if (turma == null)
            {
                return NotFound();
            }
            ViewData["atividadeID"] = new SelectList(_context.Set<Atividade>(), "Id", "Nome", turma.atividadeID);
            return View(turma);
        }

        // POST: Turmas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,descricao,periodo,atividadeID")] Turma turma)
        {
            if (id != turma.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurmaExists(turma.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["atividadeID"] = new SelectList(_context.Set<Atividade>(), "Id", "Nome", turma.atividadeID);
            return View(turma);
        }

        // GET: Turmas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turma = await _context.Turma
                .Include(t => t.atidade)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (turma == null)
            {
                return NotFound();
            }

            return View(turma);
        }

        // POST: Turmas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var turma = await _context.Turma.FindAsync(id);
            if (turma != null)
            {
                _context.Turma.Remove(turma);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TurmaExists(int id)
        {
            return _context.Turma.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CurricularizacaoADS2024</title>

    <!-- CSS Links -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CurricularizacaoADS2024.styles.css" asp-append-version="true" />

    <style>
        /* Navbar Styling */
        .navbar {
            background: linear-gradient(to right, #0062E6, #33AEFF);
        }

        .navbar-toggler {
            border: none; /* Remove border */
            background-color: #ffffff; /* Botão branco */
            margin-left: auto;
            color: #007BFF; /* Ícone azul */
        }

        .navbar-toggler-icon {
            background-color: #007BFF; /* Ajuste a cor do ícone para melhor visibilidade */
        }

        .navbar-nav .nav-item .nav-link {
            background-color: #007BFF;
            color: white !important;
            border-radius: 5px;
            transition: background-color 0.3s ease, transform 0.3s ease;
        }

            .navbar-nav .nav-item .nav-link:hover {
                background-color: #0056b3;
                color: #FFD700 !important;
                transform: scale(1.05);
            }

        .container {
            color: black;
            text-align: center;
            margin: 0 auto;
        }

        footer {
            background-color: #123456;
            color: #fff;
            border-top: 2px solid #f8f9fa;
        }

            footer .container {
                font-size: 1rem;
            }
        /* Section Highlight */
        .highlight-text {
            background-color: #f8f9fa;
            padding: 10px 15px;
            border-radius: 8px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            font-size: 1.25rem;
            font-weight: bold;
            color: #333;
        }
        /* Cards */
        .card {
            border-radius: 10px;
            box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            padding: 2rem;
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100 bg-light">
    <header>
        
        <nav class="navbar navbar-dark bg-dark fixed-top">

            <div class="container-fluid">

                <div class="nav-item">
                    <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house-door me-2"></i> Home
                    </a>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"></h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Matriculas" asp-action="Index">Matricula</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Responsavel" asp-action="Index">Responsavel</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Visitas" asp-action="Index">Visitas</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Turmas" asp-action="Index">Turmas</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Atividades" asp-action="Index">Atividade</a>
                            </li>                           

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Parceiros" asp-action="Index">Parceiros</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-light text-dark nav-link me-2 mb-2 mb-lg-0" asp-area="" asp-controller="Professor" asp-action="Index">Professores</a>
                            </li>





                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Filtrar
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li class="nav-item">
                                        <a class="btn btn-light text-dark nav-link me-2" asp-area="" asp-controller="Consultas" asp-action="FiltrarVisita">Filtrar Visita</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="btn btn-light text-dark nav-link me-2" asp-area="" asp-controller="Consultas" asp-action="FiltrarMatricula">Filtrar Matricula</a>
                                    </li>
                                    
                                </ul>
                            </li>
                        </ul>

                        

                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-5 flex-grow-1">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CurricularizacaoADS2024
        </div>
    </footer>

    <!-- Script Links -->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>